sudo: required
services:
  - docker

before_install:
  - docker build . -f Dockerfile.dev -t debugme/dgta

script:
  - docker run -e CI=true -it debugme/dgta npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-github-travis-aws
  env: DockerGithubTravisAws-env
  bucket_name: elasticbeanstalk-us-east-1-299685737057
  bucket_path: docker-github-travis-aws
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
