version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - /app/node_modules
      - "./src:/app/src"
      - "./public:/app/public"
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - "./src:/app/src"
      - "./public:/app/public"
    command: ["npm", "run", "test"]
